name:                prospect
version:             0.1.0.0
github:              "isovector/prospect"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2018 Sandy Maguire"
tested-with:         GHC == 8.0.2, GHC == 8.2.1

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Explore continuations with trepidation
category:            Control

description:         Please see the README on GitHub at <https://github.com/isovector/prospect#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl
    - transformers
    - free
    - kan-extensions
    - deepseq

tests:
  prospect-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prospect
    - hspec
    - free
    - kan-extensions
    - inspection-testing
    - deepseq
