name:                accursed
version:             0.1.0.0
github:              "isovector/accursed"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2018 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Explore continuations with trepidation
category:            Control

description:         Please see the README on GitHub at <https://github.com/isovector/accursed#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl
    - transformers
    - free
    - kan-extensions

tests:
  accursed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accursed
    - hspec
    - free
    - kan-extensions
    - inspection-testing
    - deepseq
